---
title: "eds223-week10"
format: html
editor: visual
---
---
title: "week10-eds223"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## 
```{r}
# Load libraries

library(terra)
library(sf)
library(tidyverse)
library(tmap)
library(here)
```

```{r}
# digital surface model (DSM)
dsm <- rast(here::here("data", "SJER2013_DSM.tif"))

# digital terrain model (DTM)
dtm <- rast(here::here("data", "SJER2013_DTM.tif"))
```

```{r}
# The easiest way to test if two rasters are matching is to try and stack them

test_raster <- c(dsm, dtm)

# We want to subtract so we can tell the differnce
# Create canopy height model
# functionally is just surface - terrain 
chm <- dsm - dtm
```

## Load Vegetations Plot Geometries

```{r}
# read in plot centroids
plot_centroids <- st_read(here::here("data", "PlotCentroids", "SJERPlotCentroids_Buffer.shp")) %>%
  st_transform(., crs = st_crs(chm))

# test if the plot CRS matches the Lidar CRS
if(st_crs(plot_centroids) == st_crs(chm)) {
  print("coordinate reference systems match")
} else{
  plot_centroids <- st_transform(plot_centroids, crs = st_crs(chm))
}
```

```{r}
# Plot estimates of the height of the canopy 
tm_shape(chm) +
  tm_raster(title = "Digital surface model (m)") +
  tm_shape(plot_centroids) +
  tm_polygons()
```

## Load in Vegetation Survey

```{r}
# read in survey data and find the maximum tree height in each plot
veg_surveys <- read.csv(here("data", "VegetationData", "D17_2013_vegStr.csv")) %>%
  group_by(plotid) %>%
  summarise("survey_height" = max(stemheight, na.rm = TRUE))
```

```{r}
# Extracting/finding the height from the chm
# We are telling it to aggregate via the max function
# Extract gives us our data in a weird format, so we renaim it to chm_height
extract_chm_height <- terra::extract(chm, plot_centroids, fun = max) %>%
  rename(chm_height = SJER2013_DSM) %>%
  select(chm_height)
```

```{r}
# Update plot_centroids so that is has plot surveys? combined? We are left joing the veg_surveys
# So we have a data frame that has all of our estimates in one place.
plot_centroids <- cbind(plot_centroids, extract_chm_height) %>%
  left_join(.,veg_surveys, by = c("Plot_ID" = "plotid"))
```

```{r}
ggplot(plot_centroids, aes(x = chm_height, y = survey_height)) +
  geom_point() +
  geom_abline(slope = 1, 
              intercept = 0, 
              alpha = 0.5, 
              lty = 2) + #this is the one to one line 
  xlab("Maximum measured height (Lidar)") +
  ylab("Maximum measure height (survey)") +
  ggtitle("Validing lidar measurements") +
  theme_minimal()


```

